FROM ubuntu:noble

RUN mkdir -p /run/systemd && echo 'docker' > /run/systemd/container

SHELL ["/bin/bash", "-c"]
ENTRYPOINT ["/bin/bash"]

WORKDIR /omniverse

RUN apt update		&&\
    apt -y install git python3 cmake build-essential python3.12-venv pip xorg-dev libglib2.0-dev

RUN python3 -m venv /omniverse/venv &&\
    source /omniverse/venv/bin/activate &&\
    pip3 install pyside6 pyopengl

RUN git clone https://github.com/PixarAnimationStudios/OpenUSD.git &&\
    mkdir OpenUSD-build &&\
    source /omniverse/venv/bin/activate &&\
    pip install ipython &&\
    python3 OpenUSD/build_scripts/build_usd.py ./OpenUSD-build/ -j1 &&\
    echo export export PYTHONPATH=/omniverse/OpenUSD-build/lib/python/ >> ~/.bashrc &&\
    echo export export PATH=$PATH:/omniverse/OpenUSD-build/bin/ >> ~/.backrc 

