//
// Copyright 2024 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//

// WARNING: THIS FILE IS GENERATED BY usdGenSchema.  DO NOT EDIT.
TF_WRAP(G4VSolid);
TF_WRAP(G4Box);
TF_WRAP(G4Tubs);
TF_WRAP(G4Cons);
TF_WRAP(G4Orb);
TF_WRAP(G4BooleanSolid);
TF_WRAP(G4Subtraction);
TF_WRAP(G4Union);
TF_WRAP(G4Intersection);
TF_WRAP(G4DisplacedSolid);
TF_WRAP(G4MultiUnion);
TF_WRAP(G4Logical);
TF_WRAP(G4Assembly);
TF_WRAP(G4Placement);
TF_WRAP(G4Tokens);
